name: Semantic-version

# Run the workflow when a Pull Request is opened or when changes are pushed to master
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main

jobs:
 release:
  # Only release on push to main
  if: (github.event_name == 'push' ||  github.event_name == 'pull_request') && github.ref == 'refs/heads/main'
  runs-on: ubuntu-latest
  # Waits for test jobs to complete
  # needs: [test] // Removed as of now
  steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: Setup Node.js
    uses: actions/setup-node@v1
    with:
      node-version: 16.13.0

  - name: Release
    run: npx -p @semantic-release/commit-analyzer -p @semantic-release/release-notes-generator -p @semantic-release/changelog -p @semantic-release/git -p semantic-release semantic-release --ci true --debug --branches 'main'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #NPM_TOKEN: ${{ secrets.NPM_TOKEN }}